help.text1=Essa widget é um EXEMPLO de um Wizard de Instalação de um Oauth App para um app/componente da fluig Store.
help.text2=Sempre que um app da fluig Store necessitar de uma integração, uma alternativa será criar um OAuth App
help.text3=Nesse wizard, são criados os seguintes componentes: OAuth Provider, OAuth App. Em seguida, são gerados os tokens, accessToken e tokenSecret para essa integração.
help.obs=obs.: Caso for implementar esse wizard, não é obrigatório exibir essas informações. Apenas informe ao usuário que é uma etapa inicial de instalação/configuração. Fique à vontade para criar seu Wizard
label.info.item=Item
label.info.installed=Instalado
label.btn.install=Instalar
label.consumer.key=Consumer Key
label.consumer.secret=Consumer Secret
label.info.oauth.provider=OAuth Provider
label.info.oauth.app=OAuth App
label.info.oauth.tokens=Tokens gerados pelo fluig após criar o OAuth App
label.access.token=Access Token
label.token.secret=Token Secret
label.oa.installed=Instalado
toast.oa.installed=OAuth App criado e Tokens gerados