<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>
	<groupId>com.fluig</groupId>
	<artifactId>sample-runner</artifactId>
	<version>1.0.0</version>
	<packaging>pom</packaging>

	<name>Sample Runner</name>
	<description>Sample project for fluig Runner environment</description>

	<!-- Necessário configurar o nexus.fluig.com como repositório central de dependências -->
	<repositories>
		<repository>
			<id>nexus</id>
			<name>fluig Nexus Repository</name>
			<url>http://nexus.fluig.com/content/groups/public</url>
		</repository>
	</repositories>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<!-- INSIRA AQUI A RELEASE DO FLUIG QUE O SEU APP É COMPATÍVEL -->
		<fluig.version>1.8.3-SNAPSHOT</fluig.version>		
	</properties>

	<modules>
		<module>runner-config</module>
		<module>runner-widget</module>
		<module>runner-service</module>
		<module>runner-rest</module>
		<module>runner-pack</module>
    </modules>

	<!--Dependency Management: controla a versão das dependencias utilizadas pelo projeto -->
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>javax</groupId>
				<artifactId>javaee-api</artifactId>
				<version>8.0</version>
				<scope>provided</scope>
			</dependency>
			<dependency>
				<groupId>com.fluig</groupId>
				<artifactId>fluig-api-tools</artifactId>
				<version>1.1.0</version>
				<scope>provided</scope>
			</dependency>
			<dependency>
				<groupId>oauth.signpost</groupId>
				<artifactId>signpost-core</artifactId>
				<version>2.1.1</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-war-plugin</artifactId>
				<version>3.3.1</version>
				<configuration>
					<warSourceExcludes>**/.js,**/.css</warSourceExcludes>
					<failOnMissingWebXml>false</failOnMissingWebXml>
					<archive>
						<manifestEntries>
							<Dependencies>com.fluig.common</Dependencies>
						</manifestEntries>
					</archive>
				</configuration>
			</plugin>
			<plugin>
				<groupId>net.alchim31.maven</groupId>
				<artifactId>yuicompressor-maven-plugin</artifactId>
				<version>1.5.1</version>
				<executions>
					<execution>
						<goals>
							<goal>compress</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<excludes>
						<exclude>**/*.js</exclude>
					</excludes>
					<nosuffix>true</nosuffix>
					<force>true</force>
					<linebreakpos>-1</linebreakpos>
					<disableOptimizations>false</disableOptimizations>
					<gzip>false</gzip>
					<jswarn>false</jswarn>
					<nomunge>true</nomunge>
					<preserveAllSemiColons>false</preserveAllSemiColons>
				</configuration>
			</plugin>
			<plugin>
				<groupId>com.github.blutorange</groupId>
				<artifactId>closure-compiler-maven-plugin</artifactId>
				<version>2.21.0</version>
				<executions>
					<execution>
						<id>default-minify</id>
						<goals>
							<goal>minify</goal>
						</goals>
						<phase>generate-resources</phase>
					</execution>
				</executions>
				<configuration>
					<skip>true</skip>
					<baseSourceDir>${project.basedir}/src</baseSourceDir>
					<encoding>UTF-8</encoding>
					<sourceDir>main/webapp/resources</sourceDir>
					<targetDir>resources</targetDir>
					<includes>**/*.js</includes>
					<outputFilename>#{path}/#{basename}.#{extension}</outputFilename>
					<excludes>**/${project.basedir}</excludes>
					<excludes>**/*.min.js</excludes>
					<excludes>**/*-min.js</excludes>
					<closureCompilationLevel>SIMPLE_OPTIMIZATIONS</closureCompilationLevel>
					<closureWarningLevels>
						<undefinedVars>OFF</undefinedVars>
						<duplicate>OFF</duplicate>
						<duplicateMessage>OFF</duplicateMessage>
						<es5Strict>OFF</es5Strict>
						<checkVars>OFF</checkVars>
					</closureWarningLevels>
					<closureEmitUseStrict>false</closureEmitUseStrict>
					<closureRewritePolyfills>false</closureRewritePolyfills>
					<closureLanguageOut>NO_TRANSPILE</closureLanguageOut>
					<skipMinify>false</skipMinify>
					<skipMerge>true</skipMerge>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.2</version>
				<configuration>
					<source>11</source>
					<target>11</target>
				</configuration>
			</plugin>			
		</plugins>
		<finalName>${project.artifactId}</finalName>
	</build>

</project>