<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.fluig</groupId>
		<artifactId>sample-component</artifactId>
		<version>1.0.1</version>
	</parent>
	<artifactId>sample-component-web</artifactId>
	<packaging>war</packaging>

	<name>Sample Component - web</name>
	<description>Sample Component - web | description</description>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<dependencies>
	
		<dependency>
			<groupId>com.fluig</groupId>
			<artifactId>sample-component-api</artifactId>
			<version>${project.version}</version>
		</dependency>
		
		<!-- Fluig Dependencies -->
		<dependency>
			<groupId>com.fluig</groupId>
			<artifactId>fluig-sdk-api</artifactId>
			<version>${fluig.version}</version>			
		</dependency>
		<dependency>
			<groupId>com.fluig</groupId>			
			<artifactId>fluig-swagger-ui</artifactId>
			<version>${fluig.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.fluig</groupId>
			<artifactId>fluig-sdk-common</artifactId>
			<version>${fluig.version}</version>			
		</dependency>
		<!-- /Fluig Dependencies -->

		<!-- Other dependencies -->
		<!-- To change version of each dependency, go to the parent sample-component/pom.xml -->
		<dependency>
			<groupId>javax</groupId>
			<artifactId>javaee-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.fluig</groupId>
			<artifactId>fluig-api-tools</artifactId>
			<scope>compile</scope>
		</dependency>
		<!-- /Other dependencies -->

	</dependencies>

	<build>
		<finalName>sample-component-web</finalName>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.2</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>com.github.kongchen</groupId>
				<artifactId>swagger-maven-plugin</artifactId>
				<version>3.1.5</version>
				<configuration>
					<apiSources>
						<apiSource>
							<springmvc>false</springmvc>
							<locations>
								<location>com.samplecomponent.example1.rest</location>
							</locations>
							<schemes>								
								<scheme>http</scheme>
								<scheme>https</scheme>
							</schemes>
							<basePath>/samplecomponentweb/v1</basePath>
							<info>								
								<title>Sample Component WEB API</title>
								<description>Exemplo de API Rest para o samplecomponent</description>
								<version>${project.version}</version>
							</info>
							<outputFormats>json,yaml</outputFormats>
							<swaggerDirectory>${project.build.directory}/${project.artifactId}/swagger-ui</swaggerDirectory>
							<swaggerFileName>swagger</swaggerFileName>
							<attachSwaggerArtifact>true</attachSwaggerArtifact>
							<modelConverters>com.fluig.api.tools.swagger.JSONPatchPropertyConverter</modelConverters>
						</apiSource>
					</apiSources>
				</configuration>
				<executions>
					<execution>
						<phase>compile</phase>
						<goals>
							<goal>generate</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

</project>