<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>
	<groupId>com.fluig</groupId>
	<artifactId>sample-component</artifactId>
	<version>1.0</version>	
	<packaging>pom</packaging>

	<name>Sample Component</name>
	<description>Sample Component description</description>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<!-- INSIRA AQUI A VERÃO DO FLUIG. Com base na versão que as dependências serão utilizadas -->
		<fluig.version>1.6.2</fluig.version>
	</properties>

	<modules>
		<module>sample-component-widget</module>
		<module>sample-component-web</module>
		<module>sample-component-server</module>
	</modules>
	
	<distributionManagement>
		<repository>
			<id>nexus</id>
			<name>Totvs Internal Releases</name>
			<url>http://nexus.fluig.com/content/repositories/releases</url>
		</repository>
		<snapshotRepository>
			<id>nexus</id>
			<name>Totvs Internal Snapshots</name>
			<url>http://nexus.fluig.com/content/repositories/snapshots/</url>
		</snapshotRepository>
	</distributionManagement>
	
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>javax</groupId>
				<artifactId>javaee-api</artifactId>
				<version>8.0</version>
				<scope>provided</scope>
			</dependency>
			<dependency>
				<groupId>org.apache.httpcomponents</groupId>
				<artifactId>httpclient</artifactId>
				<version>4.5.2</version>
				<scope>provided</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
		</plugins>
		<finalName>${project.artifactId}</finalName>
	</build>
</project>
