<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>
	<groupId>com.fluig</groupId>
	<artifactId>sample-component</artifactId>
	<version>1.0.2</version>
	<packaging>pom</packaging>

	<name>Sample Component</name>
	<description>Sample Component description</description>

	<!-- Necessário configurar o nexus.fluig.com como repositório central de 
		dependências -->
	<repositories>
		<repository>
			<id>nexus</id>
			<name>fluig Nexus Repository</name>
			<url>http://nexus.fluig.com/content/groups/public</url>
		</repository>
	</repositories>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<!-- INSIRA AQUI A VERÃO DO FLUIG. Com base na versão que as dependências 
			serão utilizadas -->
		<fluig.version>1.6.5</fluig.version>
	</properties>

	<modules>
		<module>sample-component-layout</module>
		<module>sample-component-widget</module>
		<module>sample-component-custom-layout</module>
		<module>sample-component-menu-widget</module>
		<module>sample-component-config</module>
		<module>sample-component-service</module>
		<module>sample-component-rest</module>
		<module>sample-component-pack</module>
	</modules>

	<!--Dependency Management: controla a versão das dependencias utilizadas 
		pelo projeto -->
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>javax</groupId>
				<artifactId>javaee-api</artifactId>
				<version>8.0</version>
				<scope>provided</scope>
			</dependency>
			<dependency>
				<groupId>org.apache.httpcomponents</groupId>
				<artifactId>httpclient</artifactId>
				<version>4.5.2</version>
				<scope>provided</scope>
			</dependency>
			<dependency>
				<groupId>com.fluig</groupId>
				<artifactId>fluig-api-tools</artifactId>
				<version>1.1.0</version>
				<scope>provided</scope>
			</dependency>
			<dependency>
				<groupId>oauth.signpost</groupId>
				<artifactId>signpost-core</artifactId>
				<version>1.2.1.1</version>
			</dependency>
			<dependency>
				<groupId>org.projectlombok</groupId>
				<artifactId>lombok</artifactId>
				<version>1.18.8</version>
				<scope>provided</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.2</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
		</plugins>
		<finalName>${project.artifactId}</finalName>
	</build>
</project>