application.title=Sample Widget
label.widget.hello=Olá! Essa é uma widget de exemplo
label.button.click=Clicar
msg.alert.ok=Uma mensagem de OK!
msg.today.is=Hoje é
label.button.load.table=Carregar tabela
msg.remove.selected.user=Deseja remover o usuário selecionado?
label.remove.user=Remover usuário
label.yes=Sim
label.no=Não
label.button.sample.rest.external=API Rest externa
label.button.sample.create.category=Criar categoria
label.button.sample.list.categories=Listar categorias
label.license.ok=SlotID válido. License OK
label.license.non.ok=SlotID inválido. License NON OK
label.name=Nome
label.login=login
label.address=Endereço
label.email=email
label.phone=Telefone
label.delete=Excluir
label.edit=Editar
label.id=ID
msg.welcome=Olá {0}. Seja bem-vindo!
ph.category.name=Nome da categoria
msg.category.name.required=Nome da categoria é obrigatório
msg.category.name.max.length=Nome da categoria com no máximo de 50 caracteres
msg.error.create.category=Ocorreu um erro ao criar a categoria: {0}
category.created=Categoria criada
btn-category.create=Criar
