application.title=GRD Custom - Nova publicação
application.description=Crie publicações em comunidades.
follower=Seguidor
shareplace.title=Mural
post.picture=Publicar imagem
post.video=Publicar Vídeo
public=Público
private=Privado
share.question=O que deseja compartilhar?
publish=Publicar
no.document.method=Não há método para documentos no momento
file.already.attached=Já existe um arquivo anexado
min.two.chars=A mensagem precisa possuir pelo menos dois caracteres
member=Membro
post.error=Ocorreu um erro ao realizar o post
post.document=Publicar documento
select.document=Selecionar documento
insert=Inserir
profile.disabled=Perfil desabilitado
community.disabled=Comunidade desativada. Disponível apenas para consulta.
user.disabled=Usuário desativado. Disponível somente para consulta.
new=Novo
application.category=Social
post.error.social=Não foi possível finalizar a operação.
post.error.social.member=Não foi possível verificar se o usuário é membro da comunidade.
post.error.user.logged=Não foi possível recuperar o usuário logado.
post.error.document.enabled=Não foi possível verificar se o recurso está disponível.

## EDIT
context.publish=Contexto
context.followers=Seguidores
context.community=Comunidade
selected.community=Comunidade selecionada:
enter.community=Informe a comunidade
btn.save=Salvar
successs.update=Configurações salvas
select.community=Selecione a comunidade para associar o contexto.
poster.shared.with=Esse conteúdo será compartilhado com
poster.my.followers=meus seguidores
unavailable.poster=Publicação inacessível
contact.administrator=Entre em contato com o administrador para obter mais informações sobre restrições de acesso.
user.not.participant=Voc\u00EA n\u00E3o pertence ao mesmo grupo de acesso.
attention=Atenção!