help.text1=Essa widget é um EXEMPLO de um Wizard de Instalação de um Processo com Formulário para um app/componente da fluig Store.
help.text2=Sempre que um app da fluig Store necessitar de um processo para seu funcionamento, é necessário que esse processo já esteja disponíveis no fluig. Para isso, é recomendando que todo app possua um wizard inicial de instalação/configuração, onde esse processo será criado antes mesmo que o app seja utilizado pela primeira vez.
help.text3=Para a instalação tanto do formulário quanto do processo, é necessário transformar o conteúdo dos arquivos(html e xml) em Base64 de forma dinâmica. Para isso, é utilizado uma biblioteca JS.
help.obs=obs.: Caso for implementar esse wizard, não é obrigatório exibir essas informações. Apenas informe ao usuário que é uma etapa inicial de instalação/configuração. Fique à vontade para criar seu Wizard
label.install=Instalar
label.process.installed=Componente instalado
label.info.item=Item
label.info.installed=Instalado
label.info.group=Grupo de usuários
label.info.folder=Pasta para o formulário
label.info.form=Formulário Simples
label.info.process=Processo Simples
label.info.no.installed=Não instalado
label.info.go=Clique em instalar para criar os itens acima
msg.alert.items.created=Itens criados. Componente pronto para o uso
msg.alert.unexpect_error=Erro Inesperado