<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.fluig</groupId>
		<artifactId>sample-component</artifactId>
		<version>1.0.2</version>
	</parent>
	<artifactId>sample-component-pack</artifactId>
	<packaging>ear</packaging>

	<name>Sample Component - pack</name>
	<description>Modulo para empacotar o projeto Sample Component</description>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<dependencies>
		<dependency>
			<groupId>com.fluig</groupId>
			<artifactId>foundation-common</artifactId>
			<version>${fluig.version}</version>
		</dependency>
		<dependency>
			<groupId>com.fluig</groupId>
			<artifactId>foundation-cache-module</artifactId>
			<version>${fluig.version}</version>
		</dependency>
		<dependency>
			<groupId>com.fluig</groupId>
			<artifactId>sample-component-widget</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
			<type>war</type>
		</dependency>
		<dependency>
			<groupId>com.fluig</groupId>
			<artifactId>sample-component-layout</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
			<type>war</type>
		</dependency>
		<dependency>
			<groupId>com.fluig</groupId>
			<artifactId>sample-component-custom-layout</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
			<type>war</type>
		</dependency>
		<dependency>
			<groupId>com.fluig</groupId>
			<artifactId>sample-component-menu-widget</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
			<type>war</type>
		</dependency>
		<dependency>
			<groupId>com.fluig</groupId>
			<artifactId>sample-component-config</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
			<type>war</type>
		</dependency>
		<dependency>
			<groupId>com.fluig</groupId>
			<artifactId>sample-component-entity</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
			<type>jar</type>
		</dependency>
		<dependency>
			<groupId>com.fluig</groupId>
			<artifactId>sample-component-service</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
			<type>ejb</type>
		</dependency>
		<dependency>
			<groupId>com.fluig</groupId>
			<artifactId>sample-component-rest</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
			<type>war</type>
		</dependency>
		<dependency>
			<groupId>javax</groupId>
			<artifactId>javaee-api</artifactId>
		</dependency>
		<dependency>
			<groupId>com.fluig</groupId>
			<artifactId>fluig-api-tools</artifactId>
		</dependency>
	</dependencies>

	<build>
		<resources>
			<resource>
				<directory>src/main/application/META-INF</directory>
				<filtering>true</filtering>
			</resource>
		</resources>
		<finalName>sample-component</finalName>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.2</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-ear-plugin</artifactId>
				<version>2.10</version>
				<configuration>
					<version>6</version>
					<applicationName>Sample_Component</applicationName>
					<generateModuleId>false</generateModuleId>
					<defaultLibBundleDir>lib</defaultLibBundleDir>
					<initializeInOrder>true</initializeInOrder>
					<fileNameMapping>full</fileNameMapping>
					<security>
						<security-role>
							<role-name>sysadmin</role-name>
						</security-role>
						<security-role>
							<role-name>admin</role-name>
						</security-role>
						<security-role>
							<role-name>user</role-name>
						</security-role>
					</security>
					<modules>
						<webModule>
							<groupId>com.fluig</groupId>
							<artifactId>sample-component-layout</artifactId>
							<contextRoot>/samplelayout</contextRoot>
						</webModule>
						<webModule>
							<groupId>com.fluig</groupId>
							<artifactId>sample-component-custom-layout</artifactId>
							<contextRoot>/samplecustomlayout</contextRoot>
						</webModule>
						<webModule>
							<groupId>com.fluig</groupId>
							<artifactId>sample-component-menu-widget</artifactId>
							<contextRoot>/samplewidgetmenu</contextRoot>
						</webModule>
						<webModule>
							<groupId>com.fluig</groupId>
							<artifactId>sample-component-widget</artifactId>
							<contextRoot>/samplewidget</contextRoot>
						</webModule>
						<webModule>
							<groupId>com.fluig</groupId>
							<artifactId>sample-component-rest</artifactId>
							<contextRoot>/samplerest</contextRoot>
						</webModule>
						<webModule>
							<groupId>com.fluig</groupId>
							<artifactId>sample-component-config</artifactId>
							<contextRoot>/samplecomponentconfig</contextRoot>
						</webModule>
					</modules>
				</configuration>
			</plugin>
		</plugins>
		<sourceDirectory>${java.src.dir}</sourceDirectory>
	</build>


</project>
