help.text1=Essa widget é um EXEMPLO de um Wizard de Instalação de Datasets para um app/componente da fluig Store.
help.text2=Sempre que um app da fluig Store necessitar de datasets para persistir algum dado, é necessário que esses datasets já estejam disponíveis no fluig. Para isso, é recomendando que todo app possua um wizard inicial de instalação/configuração, onde esses datasets são previamente criados antes mesmo que o app seja utilizado pela primeira vez.
help.text3=Nesse wizard, são criados os seguintes datasets com seus respectivos campos. Além disso, existe a opção de criá-los no modo Sincronizado. Note que apenas os datasets são criados e não os formulários:
help.obs=obs.: Caso for implementar esse wizard, n\u00E3o \u00E9 obrigat\u00F3rio exibir essas informa\u00E7\u00F5es. Apenas informe ao usu\u00E1rio que \u00E9 uma etapa inicial de instala\u00E7\u00E3o/configura\u00E7\u00E3o. Fique \u00E0 vontade para criar um Wizard de acordo com o app
label.btn.install=Instalar
label.yes=Sim
label.no=Não
label.dt.code=Código
label.dt.fields=Campos
label.dt.sync=Sincronizado
label.dt.installed=Instalado
toast.dt.installed=Dataset instalado
help.link=Acesse a p\u00E1gina de Datasets para verificar os datasets j\u00E1 dispon\u00EDveis no fluig