application.title=Sample Widget
label.widget.hello=Olá! Essa é uma widget simples
label.button.click=Clicar
msg.alert.ok=Uma mensagem de OK!
msg.today.is=Hoje é
label.button.load.table=Carregar tabela
msg.remove.selected.user=Deseja remove o usuário selecionado?
label.remove.user=Remover usuário
label.yes=Sim
label.no=Não
label.button.sample.rest.external=API Rest externa
label.button.sample.rest.internal=API Rest interna
label.license.ok=SlotID válido. License OK
label.license.non.ok=SlotID inválido. License NON OK